### ISSUE TITLE
Unfurl links in the original issue/pr body

### ISSUE THREAD

**Issue by bkeepers** [probot/unfurl#1]
Currently only unfurls links in comments.

**Comment by rsarky** [comment]
I would like to work on this.
Is this issue still relevant?

**Comment by bkeepers** [comment]
@rsarky yep! Go for it! It should be pretty easy to implement, so let me know if you have any questions.

**Comment by rsarky** [comment]
Do I have to use localtunnel instead of smee for this?

**Comment by bkeepers** [comment]
I updated to the latest probot in #12. You should be good to go now.
