### ISSUE TITLE
Avoid unfurling duplicate links

### ISSUE THREAD

**Issue by bkeepers** [probot/unfurl#21]
If the same link is included in a comment multiple times, it will be unfurled multiple times.

Example from https://github.com/probot/probot/pull/498#issuecomment-381332294:

<img width="730" alt="added_events_and_related_actions_by_aps120797_ _pull_request__498_ _probot_probot" src="https://user-images.githubusercontent.com/173/38769257-50208200-3fc5-11e8-8029-3f59eb9568aa.png">

**Comment by nesl247** [comment]
Yes this is still relevant. There is a PR for it already as well.

**Comment by hiimbex** [comment]
Closed via #24
