### ISSUE TITLE
Add config for max number of auto-unfurls

### ISSUE THREAD

**Issue by JasonEtco** [probot/unfurl#3]
This is super dope. I can see it becoming a problem in really long comments with a ton of links - can there be a config that says "if you've already added `x` links, don't add more"?

**Comment by bkeepers** [comment]
Yeah, I like that. I think we could default it to only unfurling 5-10 links. I can't imagine more than that would be useful. I'd also like to change the behavior when there are >2 links to switch to a more compact layout with 1-line for each unfurl.

**Comment by JasonEtco** [comment]
I love the idea for a "compact" layout. It should be an option in [attachments](https://github.com/probot/attachments), and `unfurl` should just switch that on with >X links.

**Comment by knrt10** [comment]
@bkeepers @JasonEtco Please review my PR. 
Thanks in advance.
