### ISSUE TITLE
Prefix urls with base path

### ISSUE THREAD

**Issue by bkeepers** [probot/unfurl#4]
https://github.com/probot/test/issues/27#issuecomment-339940545 has this unfurl:

<blockquote><img src="http://githubfieldday.com/sf2017/assets/card.png" width="48" align="right"><div><img src="/sf2017/assets/favicon-16x16.png" height="14"> GitHub Field Day</div><div><strong><a href="http://githubfieldday.com/sf2017/">GitHub Field Day</a></strong></div><div>An unconference for leaders of technical student communities. July 29 at GitHub HQ in SF.
</div></blockquote>

The icon points to `/sf2017/assets/favicon-16x16.png`, which needs to be prefixed with the base URL of the site.

**Comment by knrt10** [comment]
@bkeepers Would you please describe more to this issue?

**Comment by knrt10** [comment]
https://githubfieldday.com/sf2017/

**Comment by knrt10** [comment]
https://githubfieldday.com/sf2017/

**Comment by knrt10** [comment]
http://freecodecamp.org/knrt10

**Comment by knrt10** [comment]
@bkeepers the problem is occuring only in this case. Rest other links are returning icon to `https://*`

**Comment by knrt10** [comment]
@aryannarora It won't affect anything cause the change will be reflected only for this URL, cause rest URL return icon URL just fine.
