### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by Mike-E-wins** [probot/unfurl#45]
Hey there... we saw this app and thought it was cool and installed it on our repo.  unfortunately it looks like we posted an issue with a link, and it didn't unfurl:

https://github.com/ExtendedXmlSerializer/ExtendedXmlSerializer/issues/313#issue-527035959

Are we doing something wrong? :)

Thank you for any assistance/guidance. 👍

**Comment by Mike-EEE** [comment]
Ah I posted a reply to that issue and it unfurled correctly.  So it would seem this is a bug that impacts the original issue.

**Comment by Mike-EEE** [comment]
I would think so?  It seems links posted in the original post are not unfurling.  Seems like a significant issue as first impressions are everything. :)
