### ISSUE TITLE
Uncorrect Unfurl for GitHub Release

### ISSUE THREAD

**Issue by Mike-E-wins** [probot/unfurl#47]
Hey there... we just released a new version on GitHub, and in pasting the links throughout our repository to let people know where to find the release notes, it seems unfurl is not properly unfurling the link.

Here is an example:

https://github.com/ExtendedXmlSerializer/home/issues/269#issuecomment-561053770

it appears unfurl unfurls:

```
https://github.com/ExtendedXmlSerializer/home
```

Rather than:

```
https://github.com/ExtendedXmlSerializer/home/releases/tag/3.0.0
```

Everything else looks like it's working, however. 👍

**Comment by Mike-EEE** [comment]
This place ded. 😆
